version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: alma-inventory-purdue
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
      - ./alias.conf:/etc/apache2/mods-available/alias.conf
#     - ./key_rmc.php:/srv/app/key_rmc.php
#     - ./key_mmc.php:/srv/app/key_mmc.php
